version: "3"
services:
  aliyun-docker-trigger:
    image: registry.cn-hangzhou.aliyuncs.com/your_username/aliyun-docker-trigger:latest
    volumes:
      - ./dockerfiles:/app/dockerfiles
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
    ports:
      - 8080:80
